// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Deterministic pagination outcome for one section.
class PaginationResult {
  final BigInt sectionIndex;
  final BigInt totalPages;
  final String pageMapDebug;
  final bool isRtl;

  const PaginationResult({
    required this.sectionIndex,
    required this.totalPages,
    required this.pageMapDebug,
    required this.isRtl,
  });

  @override
  int get hashCode =>
      sectionIndex.hashCode ^
      totalPages.hashCode ^
      pageMapDebug.hashCode ^
      isRtl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginationResult &&
          runtimeType == other.runtimeType &&
          sectionIndex == other.sectionIndex &&
          totalPages == other.totalPages &&
          pageMapDebug == other.pageMapDebug &&
          isRtl == other.isRtl;
}

/// Render-ready section payload. `html` is library-processed section HTML;
/// the Flutter renderer sanitizes it and never executes scripts.
class SectionContent {
  final BigInt index;
  final String idref;
  final String href;
  final String html;
  final String plainText;
  final BigInt charCount;
  final List<SectionImage> images;

  const SectionContent({
    required this.index,
    required this.idref,
    required this.href,
    required this.html,
    required this.plainText,
    required this.charCount,
    required this.images,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      idref.hashCode ^
      href.hashCode ^
      html.hashCode ^
      plainText.hashCode ^
      charCount.hashCode ^
      images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectionContent &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          idref == other.idref &&
          href == other.href &&
          html == other.html &&
          plainText == other.plainText &&
          charCount == other.charCount &&
          images == other.images;
}

/// One lazily retrieved bitmap used by the current section/page.
///
/// HTML-backed formats use `source` to match an image tag to its archive
/// bytes. PDF images use a synthetic source and include page placement data.
class SectionImage {
  final String source;
  final String mimeType;
  final Uint8List data;
  final int pixelWidth;
  final int pixelHeight;
  final String dataFormat;
  final double left;
  final double top;
  final double displayWidth;
  final double displayHeight;
  final double pageWidth;
  final double pageHeight;
  final int rotationDegrees;

  const SectionImage({
    required this.source,
    required this.mimeType,
    required this.data,
    required this.pixelWidth,
    required this.pixelHeight,
    required this.dataFormat,
    required this.left,
    required this.top,
    required this.displayWidth,
    required this.displayHeight,
    required this.pageWidth,
    required this.pageHeight,
    required this.rotationDegrees,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      mimeType.hashCode ^
      data.hashCode ^
      pixelWidth.hashCode ^
      pixelHeight.hashCode ^
      dataFormat.hashCode ^
      left.hashCode ^
      top.hashCode ^
      displayWidth.hashCode ^
      displayHeight.hashCode ^
      pageWidth.hashCode ^
      pageHeight.hashCode ^
      rotationDegrees.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectionImage &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          mimeType == other.mimeType &&
          data == other.data &&
          pixelWidth == other.pixelWidth &&
          pixelHeight == other.pixelHeight &&
          dataFormat == other.dataFormat &&
          left == other.left &&
          top == other.top &&
          displayWidth == other.displayWidth &&
          displayHeight == other.displayHeight &&
          pageWidth == other.pageWidth &&
          pageHeight == other.pageHeight &&
          rotationDegrees == other.rotationDegrees;
}
