// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Deterministic pagination outcome for one section.
class PaginationResult {
  final BigInt sectionIndex;
  final BigInt totalPages;
  final String pageMapDebug;
  final bool isRtl;

  const PaginationResult({
    required this.sectionIndex,
    required this.totalPages,
    required this.pageMapDebug,
    required this.isRtl,
  });

  @override
  int get hashCode =>
      sectionIndex.hashCode ^
      totalPages.hashCode ^
      pageMapDebug.hashCode ^
      isRtl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaginationResult &&
          runtimeType == other.runtimeType &&
          sectionIndex == other.sectionIndex &&
          totalPages == other.totalPages &&
          pageMapDebug == other.pageMapDebug &&
          isRtl == other.isRtl;
}

/// Render-ready section payload. `html` is library-processed section HTML;
/// the Flutter renderer sanitizes it and never executes scripts.
class SectionContent {
  final BigInt index;
  final String idref;
  final String href;
  final String html;
  final String plainText;
  final BigInt charCount;

  const SectionContent({
    required this.index,
    required this.idref,
    required this.href,
    required this.html,
    required this.plainText,
    required this.charCount,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      idref.hashCode ^
      href.hashCode ^
      html.hashCode ^
      plainText.hashCode ^
      charCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectionContent &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          idref == other.idref &&
          href == other.href &&
          html == other.html &&
          plainText == other.plainText &&
          charCount == other.charCount;
}
