// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Progress snapshot: library-native progression values (supplementary)
/// plus the authoritative locator JSON (primary restore key).
class ProgressInfo {
  final BigInt sectionIndex;
  final BigInt charOffset;
  final double progression;
  final double totalProgression;
  final String locatorJson;

  const ProgressInfo({
    required this.sectionIndex,
    required this.charOffset,
    required this.progression,
    required this.totalProgression,
    required this.locatorJson,
  });

  @override
  int get hashCode =>
      sectionIndex.hashCode ^
      charOffset.hashCode ^
      progression.hashCode ^
      totalProgression.hashCode ^
      locatorJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressInfo &&
          runtimeType == other.runtimeType &&
          sectionIndex == other.sectionIndex &&
          charOffset == other.charOffset &&
          progression == other.progression &&
          totalProgression == other.totalProgression &&
          locatorJson == other.locatorJson;
}

/// A restored position: section + CFI + href. The CFI string is the stable
/// anchor; section index is the fast path for content fetching.
class RestoredLocation {
  final BigInt sectionIndex;
  final String cfi;
  final String href;

  const RestoredLocation({
    required this.sectionIndex,
    required this.cfi,
    required this.href,
  });

  @override
  int get hashCode => sectionIndex.hashCode ^ cfi.hashCode ^ href.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoredLocation &&
          runtimeType == other.runtimeType &&
          sectionIndex == other.sectionIndex &&
          cfi == other.cfi &&
          href == other.href;
}
