// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One navigable chapter: TOC entry preferred, spine fallback.
class ChapterInfo {
  final BigInt index;
  final String title;
  final String href;
  final BigInt depth;

  const ChapterInfo({
    required this.index,
    required this.title,
    required this.href,
    required this.depth,
  });

  @override
  int get hashCode =>
      index.hashCode ^ title.hashCode ^ href.hashCode ^ depth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          title == other.title &&
          href == other.href &&
          depth == other.depth;
}

/// Document-level info. Plain data only — no engine types cross FRB.
class DocumentInfo {
  final String title;
  final List<String> authors;
  final String? language;
  final String? description;
  final String format;
  final BigInt sectionCount;
  final bool hasCover;
  final String fingerprint;

  const DocumentInfo({
    required this.title,
    required this.authors,
    this.language,
    this.description,
    required this.format,
    required this.sectionCount,
    required this.hasCover,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      authors.hashCode ^
      language.hashCode ^
      description.hashCode ^
      format.hashCode ^
      sectionCount.hashCode ^
      hasCover.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          authors == other.authors &&
          language == other.language &&
          description == other.description &&
          format == other.format &&
          sectionCount == other.sectionCount &&
          hasCover == other.hasCover &&
          fingerprint == other.fingerprint;
}
