// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One hit. `cfi` + `section_index` + `char_offset` restore the location
/// through the same locator model as bookmarks/progress.
class SearchHit {
  final BigInt sectionIndex;
  final String cfi;
  final BigInt charOffset;
  final String snippet;

  const SearchHit({
    required this.sectionIndex,
    required this.cfi,
    required this.charOffset,
    required this.snippet,
  });

  @override
  int get hashCode =>
      sectionIndex.hashCode ^
      cfi.hashCode ^
      charOffset.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          sectionIndex == other.sectionIndex &&
          cfi == other.cfi &&
          charOffset == other.charOffset &&
          snippet == other.snippet;
}
