// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../reader/content.dart';
import '../reader/locator.dart';
import '../reader/metadata.dart';
import '../reader/search.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'reader.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Open a book file. Creates exactly one session; caller must `close_book`.
Future<OpenBookResult> openBook({required String path}) =>
    RustLib.instance.api.crateApiReaderOpenBook(path: path);

/// Close a session. Idempotent: closing twice reports success with `false`.
Future<bool> closeBook({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiReaderCloseBook(sessionId: sessionId);

/// Live session count (lifecycle/soak observability).
Future<BigInt> liveSessionCount() =>
    RustLib.instance.api.crateApiReaderLiveSessionCount();

/// Cover image for an open session (`None` when the book has none).
/// Bytes are written to app-private storage by the caller, never to
/// `Downloads/CodarLib/`.
Future<CoverImage?> getCover({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiReaderGetCover(sessionId: sessionId);

/// Document info for an open session.
Future<DocumentInfo> getDocumentInfo({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiReaderGetDocumentInfo(sessionId: sessionId);

/// Chapters (TOC depth-first, spine fallback).
Future<List<ChapterInfo>> getChapters({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiReaderGetChapters(sessionId: sessionId);

/// Section content by spine/section index.
Future<SectionContent> getContent({
  required BigInt sessionId,
  required BigInt sectionIndex,
}) => RustLib.instance.api.crateApiReaderGetContent(
  sessionId: sessionId,
  sectionIndex: sectionIndex,
);

/// Section index for a spine/manifest href (`None` when unknown).
/// Used to jump from TOC chapters to content without probing.
Future<BigInt?> findSection({
  required BigInt sessionId,
  required String href,
}) => RustLib.instance.api.crateApiReaderFindSection(
  sessionId: sessionId,
  href: href,
);

/// Page access. For PDF/CBZ one section IS one page; for reflowable formats
/// the caller pages via `paginate_section` instead.
Future<SectionContent> getPage({
  required BigInt sessionId,
  required BigInt pageIndex,
}) => RustLib.instance.api.crateApiReaderGetPage(
  sessionId: sessionId,
  pageIndex: pageIndex,
);

/// Full-text search. Every hit carries section index + CFI + char offset.
Future<List<SearchHit>> search({
  required BigInt sessionId,
  required String query,
}) => RustLib.instance.api.crateApiReaderSearch(
  sessionId: sessionId,
  query: query,
);

/// Canonical Readium locator JSON for (section, char offset).
Future<String> getLocator({
  required BigInt sessionId,
  required BigInt sectionIndex,
  required BigInt charOffset,
}) => RustLib.instance.api.crateApiReaderGetLocator(
  sessionId: sessionId,
  sectionIndex: sectionIndex,
  charOffset: charOffset,
);

/// Restore a persisted Readium locator JSON to a live location.
Future<RestoredLocation> restoreLocator({
  required BigInt sessionId,
  required String locatorJson,
}) => RustLib.instance.api.crateApiReaderRestoreLocator(
  sessionId: sessionId,
  locatorJson: locatorJson,
);

/// Progress snapshot: authoritative locator JSON + supplementary progression.
Future<ProgressInfo> getProgress({
  required BigInt sessionId,
  required BigInt sectionIndex,
  required BigInt charOffset,
}) => RustLib.instance.api.crateApiReaderGetProgress(
  sessionId: sessionId,
  sectionIndex: sectionIndex,
  charOffset: charOffset,
);

/// Deterministic reflow pagination for one section.
Future<PaginationResult> paginateSection({
  required BigInt sessionId,
  required BigInt sectionIndex,
  required int fontSizePx,
  required double lineHeight,
  required int viewportWidthPx,
  required int viewportHeightPx,
  required int marginPx,
}) => RustLib.instance.api.crateApiReaderPaginateSection(
  sessionId: sessionId,
  sectionIndex: sectionIndex,
  fontSizePx: fontSizePx,
  lineHeight: lineHeight,
  viewportWidthPx: viewportWidthPx,
  viewportHeightPx: viewportHeightPx,
  marginPx: marginPx,
);

/// Cover image payload (bytes + MIME). `None` when the book has no cover.
class CoverImage {
  final String mime;
  final Uint8List data;

  const CoverImage({required this.mime, required this.data});

  @override
  int get hashCode => mime.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverImage &&
          runtimeType == other.runtimeType &&
          mime == other.mime &&
          data == other.data;
}

/// Result of opening a book: session handle + first-glance info.
class OpenBookResult {
  final BigInt sessionId;
  final DocumentInfo info;

  const OpenBookResult({required this.sessionId, required this.info});

  @override
  int get hashCode => sessionId.hashCode ^ info.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenBookResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          info == other.info;
}

@freezed
sealed class ReaderError with _$ReaderError implements FrbException {
  const ReaderError._();

  const factory ReaderError.invalidPath(String field0) =
      ReaderError_InvalidPath;
  const factory ReaderError.unsupportedFormat(String field0) =
      ReaderError_UnsupportedFormat;
  const factory ReaderError.openFailed(String field0) = ReaderError_OpenFailed;
  const factory ReaderError.unknownSession(BigInt field0) =
      ReaderError_UnknownSession;
  const factory ReaderError.invalidSection(BigInt field0) =
      ReaderError_InvalidSection;
  const factory ReaderError.contentFailed(String field0) =
      ReaderError_ContentFailed;
  const factory ReaderError.searchFailed(String field0) =
      ReaderError_SearchFailed;
  const factory ReaderError.locatorFailed(String field0) =
      ReaderError_LocatorFailed;
  const factory ReaderError.paginationFailed(String field0) =
      ReaderError_PaginationFailed;
}
