// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/reader.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'reader/content.dart';
import 'reader/locator.dart';
import 'reader/metadata.dart';
import 'reader/search.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1172615485;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'codar_reader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiReaderCloseBook({required BigInt sessionId});

  Future<BigInt?> crateApiReaderFindSection({
    required BigInt sessionId,
    required String href,
  });

  Future<List<ChapterInfo>> crateApiReaderGetChapters({
    required BigInt sessionId,
  });

  Future<SectionContent> crateApiReaderGetContent({
    required BigInt sessionId,
    required BigInt sectionIndex,
  });

  Future<CoverImage?> crateApiReaderGetCover({required BigInt sessionId});

  Future<DocumentInfo> crateApiReaderGetDocumentInfo({
    required BigInt sessionId,
  });

  Future<String> crateApiReaderGetLocator({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required BigInt charOffset,
  });

  Future<SectionContent> crateApiReaderGetPage({
    required BigInt sessionId,
    required BigInt pageIndex,
  });

  Future<ProgressInfo> crateApiReaderGetProgress({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required BigInt charOffset,
  });

  Future<BigInt> crateApiReaderLiveSessionCount();

  Future<OpenBookResult> crateApiReaderOpenBook({required String path});

  Future<PaginationResult> crateApiReaderPaginateSection({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required int fontSizePx,
    required double lineHeight,
    required int viewportWidthPx,
    required int viewportHeightPx,
    required int marginPx,
  });

  Future<RestoredLocation> crateApiReaderRestoreLocator({
    required BigInt sessionId,
    required String locatorJson,
  });

  Future<List<SearchHit>> crateApiReaderSearch({
    required BigInt sessionId,
    required String query,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiReaderCloseBook({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderCloseBookConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderCloseBookConstMeta =>
      const TaskConstMeta(debugName: "close_book", argNames: ["sessionId"]);

  @override
  Future<BigInt?> crateApiReaderFindSection({
    required BigInt sessionId,
    required String href,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(href, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_64,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderFindSectionConstMeta,
        argValues: [sessionId, href],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderFindSectionConstMeta => const TaskConstMeta(
    debugName: "find_section",
    argNames: ["sessionId", "href"],
  );

  @override
  Future<List<ChapterInfo>> crateApiReaderGetChapters({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter_info,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetChaptersConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetChaptersConstMeta =>
      const TaskConstMeta(debugName: "get_chapters", argNames: ["sessionId"]);

  @override
  Future<SectionContent> crateApiReaderGetContent({
    required BigInt sessionId,
    required BigInt sectionIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(sectionIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_section_content,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetContentConstMeta,
        argValues: [sessionId, sectionIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetContentConstMeta => const TaskConstMeta(
    debugName: "get_content",
    argNames: ["sessionId", "sectionIndex"],
  );

  @override
  Future<CoverImage?> crateApiReaderGetCover({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_cover_image,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetCoverConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetCoverConstMeta =>
      const TaskConstMeta(debugName: "get_cover", argNames: ["sessionId"]);

  @override
  Future<DocumentInfo> crateApiReaderGetDocumentInfo({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_document_info,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetDocumentInfoConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetDocumentInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_document_info",
        argNames: ["sessionId"],
      );

  @override
  Future<String> crateApiReaderGetLocator({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required BigInt charOffset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(sectionIndex, serializer);
          sse_encode_u_64(charOffset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetLocatorConstMeta,
        argValues: [sessionId, sectionIndex, charOffset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetLocatorConstMeta => const TaskConstMeta(
    debugName: "get_locator",
    argNames: ["sessionId", "sectionIndex", "charOffset"],
  );

  @override
  Future<SectionContent> crateApiReaderGetPage({
    required BigInt sessionId,
    required BigInt pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_section_content,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetPageConstMeta,
        argValues: [sessionId, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetPageConstMeta => const TaskConstMeta(
    debugName: "get_page",
    argNames: ["sessionId", "pageIndex"],
  );

  @override
  Future<ProgressInfo> crateApiReaderGetProgress({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required BigInt charOffset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(sectionIndex, serializer);
          sse_encode_u_64(charOffset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_info,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderGetProgressConstMeta,
        argValues: [sessionId, sectionIndex, charOffset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderGetProgressConstMeta => const TaskConstMeta(
    debugName: "get_progress",
    argNames: ["sessionId", "sectionIndex", "charOffset"],
  );

  @override
  Future<BigInt> crateApiReaderLiveSessionCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReaderLiveSessionCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderLiveSessionCountConstMeta =>
      const TaskConstMeta(debugName: "live_session_count", argNames: []);

  @override
  Future<OpenBookResult> crateApiReaderOpenBook({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_open_book_result,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderOpenBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderOpenBookConstMeta =>
      const TaskConstMeta(debugName: "open_book", argNames: ["path"]);

  @override
  Future<PaginationResult> crateApiReaderPaginateSection({
    required BigInt sessionId,
    required BigInt sectionIndex,
    required int fontSizePx,
    required double lineHeight,
    required int viewportWidthPx,
    required int viewportHeightPx,
    required int marginPx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(sectionIndex, serializer);
          sse_encode_u_32(fontSizePx, serializer);
          sse_encode_f_32(lineHeight, serializer);
          sse_encode_u_32(viewportWidthPx, serializer);
          sse_encode_u_32(viewportHeightPx, serializer);
          sse_encode_u_32(marginPx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pagination_result,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderPaginateSectionConstMeta,
        argValues: [
          sessionId,
          sectionIndex,
          fontSizePx,
          lineHeight,
          viewportWidthPx,
          viewportHeightPx,
          marginPx,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderPaginateSectionConstMeta =>
      const TaskConstMeta(
        debugName: "paginate_section",
        argNames: [
          "sessionId",
          "sectionIndex",
          "fontSizePx",
          "lineHeight",
          "viewportWidthPx",
          "viewportHeightPx",
          "marginPx",
        ],
      );

  @override
  Future<RestoredLocation> crateApiReaderRestoreLocator({
    required BigInt sessionId,
    required String locatorJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(locatorJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_restored_location,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderRestoreLocatorConstMeta,
        argValues: [sessionId, locatorJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderRestoreLocatorConstMeta =>
      const TaskConstMeta(
        debugName: "restore_locator",
        argNames: ["sessionId", "locatorJson"],
      );

  @override
  Future<List<SearchHit>> crateApiReaderSearch({
    required BigInt sessionId,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_hit,
          decodeErrorData: sse_decode_reader_error,
        ),
        constMeta: kCrateApiReaderSearchConstMeta,
        argValues: [sessionId, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderSearchConstMeta => const TaskConstMeta(
    debugName: "search",
    argNames: ["sessionId", "query"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CoverImage dco_decode_box_autoadd_cover_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cover_image(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChapterInfo dco_decode_chapter_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChapterInfo(
      index: dco_decode_u_64(arr[0]),
      title: dco_decode_String(arr[1]),
      href: dco_decode_String(arr[2]),
      depth: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  CoverImage dco_decode_cover_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CoverImage(
      mime: dco_decode_String(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  DocumentInfo dco_decode_document_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DocumentInfo(
      title: dco_decode_String(arr[0]),
      authors: dco_decode_list_String(arr[1]),
      language: dco_decode_opt_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      format: dco_decode_String(arr[4]),
      sectionCount: dco_decode_u_64(arr[5]),
      hasCover: dco_decode_bool(arr[6]),
      fingerprint: dco_decode_String(arr[7]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChapterInfo> dco_decode_list_chapter_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  OpenBookResult dco_decode_open_book_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OpenBookResult(
      sessionId: dco_decode_u_64(arr[0]),
      info: dco_decode_document_info(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CoverImage? dco_decode_opt_box_autoadd_cover_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_cover_image(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PaginationResult dco_decode_pagination_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PaginationResult(
      sectionIndex: dco_decode_u_64(arr[0]),
      totalPages: dco_decode_u_64(arr[1]),
      pageMapDebug: dco_decode_String(arr[2]),
      isRtl: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ProgressInfo dco_decode_progress_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProgressInfo(
      sectionIndex: dco_decode_u_64(arr[0]),
      charOffset: dco_decode_u_64(arr[1]),
      progression: dco_decode_f_64(arr[2]),
      totalProgression: dco_decode_f_64(arr[3]),
      locatorJson: dco_decode_String(arr[4]),
    );
  }

  @protected
  ReaderError dco_decode_reader_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ReaderError_InvalidPath(dco_decode_String(raw[1]));
      case 1:
        return ReaderError_UnsupportedFormat(dco_decode_String(raw[1]));
      case 2:
        return ReaderError_OpenFailed(dco_decode_String(raw[1]));
      case 3:
        return ReaderError_UnknownSession(dco_decode_u_64(raw[1]));
      case 4:
        return ReaderError_InvalidSection(dco_decode_u_64(raw[1]));
      case 5:
        return ReaderError_ContentFailed(dco_decode_String(raw[1]));
      case 6:
        return ReaderError_SearchFailed(dco_decode_String(raw[1]));
      case 7:
        return ReaderError_LocatorFailed(dco_decode_String(raw[1]));
      case 8:
        return ReaderError_PaginationFailed(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RestoredLocation dco_decode_restored_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RestoredLocation(
      sectionIndex: dco_decode_u_64(arr[0]),
      cfi: dco_decode_String(arr[1]),
      href: dco_decode_String(arr[2]),
    );
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchHit(
      sectionIndex: dco_decode_u_64(arr[0]),
      cfi: dco_decode_String(arr[1]),
      charOffset: dco_decode_u_64(arr[2]),
      snippet: dco_decode_String(arr[3]),
    );
  }

  @protected
  SectionContent dco_decode_section_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SectionContent(
      index: dco_decode_u_64(arr[0]),
      idref: dco_decode_String(arr[1]),
      href: dco_decode_String(arr[2]),
      html: dco_decode_String(arr[3]),
      plainText: dco_decode_String(arr[4]),
      charCount: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CoverImage sse_decode_box_autoadd_cover_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cover_image(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChapterInfo sse_decode_chapter_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_depth = sse_decode_u_64(deserializer);
    return ChapterInfo(
      index: var_index,
      title: var_title,
      href: var_href,
      depth: var_depth,
    );
  }

  @protected
  CoverImage sse_decode_cover_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mime = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return CoverImage(mime: var_mime, data: var_data);
  }

  @protected
  DocumentInfo sse_decode_document_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_authors = sse_decode_list_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_sectionCount = sse_decode_u_64(deserializer);
    var var_hasCover = sse_decode_bool(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return DocumentInfo(
      title: var_title,
      authors: var_authors,
      language: var_language,
      description: var_description,
      format: var_format,
      sectionCount: var_sectionCount,
      hasCover: var_hasCover,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterInfo> sse_decode_list_chapter_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  OpenBookResult sse_decode_open_book_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_info = sse_decode_document_info(deserializer);
    return OpenBookResult(sessionId: var_sessionId, info: var_info);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CoverImage? sse_decode_opt_box_autoadd_cover_image(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_cover_image(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaginationResult sse_decode_pagination_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sectionIndex = sse_decode_u_64(deserializer);
    var var_totalPages = sse_decode_u_64(deserializer);
    var var_pageMapDebug = sse_decode_String(deserializer);
    var var_isRtl = sse_decode_bool(deserializer);
    return PaginationResult(
      sectionIndex: var_sectionIndex,
      totalPages: var_totalPages,
      pageMapDebug: var_pageMapDebug,
      isRtl: var_isRtl,
    );
  }

  @protected
  ProgressInfo sse_decode_progress_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sectionIndex = sse_decode_u_64(deserializer);
    var var_charOffset = sse_decode_u_64(deserializer);
    var var_progression = sse_decode_f_64(deserializer);
    var var_totalProgression = sse_decode_f_64(deserializer);
    var var_locatorJson = sse_decode_String(deserializer);
    return ProgressInfo(
      sectionIndex: var_sectionIndex,
      charOffset: var_charOffset,
      progression: var_progression,
      totalProgression: var_totalProgression,
      locatorJson: var_locatorJson,
    );
  }

  @protected
  ReaderError sse_decode_reader_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_InvalidPath(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_UnsupportedFormat(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_OpenFailed(var_field0);
      case 3:
        var var_field0 = sse_decode_u_64(deserializer);
        return ReaderError_UnknownSession(var_field0);
      case 4:
        var var_field0 = sse_decode_u_64(deserializer);
        return ReaderError_InvalidSection(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_ContentFailed(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_SearchFailed(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_LocatorFailed(var_field0);
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return ReaderError_PaginationFailed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RestoredLocation sse_decode_restored_location(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sectionIndex = sse_decode_u_64(deserializer);
    var var_cfi = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    return RestoredLocation(
      sectionIndex: var_sectionIndex,
      cfi: var_cfi,
      href: var_href,
    );
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sectionIndex = sse_decode_u_64(deserializer);
    var var_cfi = sse_decode_String(deserializer);
    var var_charOffset = sse_decode_u_64(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    return SearchHit(
      sectionIndex: var_sectionIndex,
      cfi: var_cfi,
      charOffset: var_charOffset,
      snippet: var_snippet,
    );
  }

  @protected
  SectionContent sse_decode_section_content(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_64(deserializer);
    var var_idref = sse_decode_String(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_html = sse_decode_String(deserializer);
    var var_plainText = sse_decode_String(deserializer);
    var var_charCount = sse_decode_u_64(deserializer);
    return SectionContent(
      index: var_index,
      idref: var_idref,
      href: var_href,
      html: var_html,
      plainText: var_plainText,
      charCount: var_charCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_cover_image(
    CoverImage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cover_image(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chapter_info(ChapterInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.index, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_u_64(self.depth, serializer);
  }

  @protected
  void sse_encode_cover_image(CoverImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mime, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_document_info(DocumentInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_u_64(self.sectionCount, serializer);
    sse_encode_bool(self.hasCover, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_info(
    List<ChapterInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_open_book_result(
    OpenBookResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_document_info(self.info, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_cover_image(
    CoverImage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_cover_image(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pagination_result(
    PaginationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sectionIndex, serializer);
    sse_encode_u_64(self.totalPages, serializer);
    sse_encode_String(self.pageMapDebug, serializer);
    sse_encode_bool(self.isRtl, serializer);
  }

  @protected
  void sse_encode_progress_info(ProgressInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sectionIndex, serializer);
    sse_encode_u_64(self.charOffset, serializer);
    sse_encode_f_64(self.progression, serializer);
    sse_encode_f_64(self.totalProgression, serializer);
    sse_encode_String(self.locatorJson, serializer);
  }

  @protected
  void sse_encode_reader_error(ReaderError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ReaderError_InvalidPath(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_UnsupportedFormat(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_OpenFailed(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_UnknownSession(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(field0, serializer);
      case ReaderError_InvalidSection(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_u_64(field0, serializer);
      case ReaderError_ContentFailed(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_SearchFailed(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_LocatorFailed(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case ReaderError_PaginationFailed(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_restored_location(
    RestoredLocation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sectionIndex, serializer);
    sse_encode_String(self.cfi, serializer);
    sse_encode_String(self.href, serializer);
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sectionIndex, serializer);
    sse_encode_String(self.cfi, serializer);
    sse_encode_u_64(self.charOffset, serializer);
    sse_encode_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_section_content(
    SectionContent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.index, serializer);
    sse_encode_String(self.idref, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_String(self.html, serializer);
    sse_encode_String(self.plainText, serializer);
    sse_encode_u_64(self.charCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
